export default [
  require('./bubbleItems/logo'),
  require('./bubbleItems/washington'),
  require('./bubbleItems/purpleStump'),
  require('./bubbleItems/play'),
  require('./bubbleItems/why'),
  require('./bubbleItems/toughQuestion'),
  require('./bubbleItems/lampshade'),
  require('./bubbleItems/mission'),
  require('./bubbleItems/dragVote'),
  require('./bubbleItems/dingell'),
  require('./bubbleItems/dragChurch'),
  require('./bubbleItems/guns'),
  require('./bubbleItems/workAmerica'),
  require('./bubbleItems/senatorWins'),
  require('./bubbleItems/godLovesFags'),
]
