export default [
  'front v2 tiny',
  'moby\'s dick',
  'and go',
  'sunrise folly',
  'unicorn-merman',
  'nola porch',
  'dorothy',
  'dreams of lucy',
  'camus cabaret',
  'arctic cries',
  'liberate yourself',
  'the flight home',
  'igbok',
  'ice cream poop',
  'eat less meat',
  'now_',
  'be your own therapy',
  'open minds v2',
  'amy',
  'prance',
  'train hoppin charlie',
  'dreams require teams',
  'b&w merman',
  'silence',
  'be',
  'dali dreams v2',
  'queer',
  'beautifully lost',
  'copacetic chaos',
  'birth is your permission',
  'di-no',
  'cosmic diversity v2',
  'diamonds',
  'submerged explorations',
  'death breath',
  'hearing voices',
  'jesus thorns',
  '1000 colors',
  'heart on fire',
  'beyond dogma',
  'use your brain',
  'fascists reign',
  'jimmy',
  'floor',
  'roark',
  'rose quartz',
  'recycle fucker',
  'always eat forbidden',
  'wrong more',
  'cosmic diversity',
  'dali dreams',
  // 'ideals',
  'dressin pretty',
]
